### ISSUE TITLE
Kinect games

### ISSUE THREAD

**Issue by ConLenov** [WinDurango-project/WinDurango#32]
Support Kinect games is planned? 

Famous Kinect games on Xbox One: Crimson Dragon, Fighter Within, Kinect Sports Rivals, Kinectimals, Kinect Andentures.

**Comment by DexrnZacAttack** [comment]
The Kinect connector isn't even USB I believe, so it's unlikely that anyone will be able to try to make it work.

**Comment by kleineluka** [comment]
Might be worth looking at [Amethyst ](https://github.com/KinectToVR/Amethyst), a Kinect to SteamVR translation layer, for how the input is taken in.

**Comment by cualquiercosa327** [comment]
Ms released the kinect v2 sdk for Windows and it is very similar (almost equal) to the one used for using kinectv2 on Xbox one.
Probably the windows drivers be enough (it only accept the device and act receiving the raw images).
The rest is done by the game (again the gesture format, classification algorithm.. is the same)

**Comment by TylerJaacks** [comment]
This is possible but is a long way away.
