### ISSUE TITLE
Add linux support

### ISSUE THREAD

**Issue by minepoof** [WinDurango-project/WinDurango#59]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I know that this is a fairly new project, and it's very early in development with only a few developers actively working on the project, but it would be pretty cool if we could get linux support eventually for this. Obviously, it would take time, but I just wanted to bring it up for the developers and contributors to take a look at.

**Additional context**
To my knowledge, this project in it's current state doesn't support linux.

**Comment by DexrnZacAttack** [comment]
There will very likely not be a native version for Linux, and any support will be dependent on Wine's WinRT implementation, which at the moment does not function.

**Comment by TylerJaacks** [comment]
This is not possible.

**Comment by Timo654** [comment]
are you sure?
https://x.com/XWineOne/status/1883901394836689276
